version: 2.1
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: node:12.13.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: apolonskyi
      - image: postgres:11.1-alpine
        environment:
          POSTGRES_HOST=localhost
          POSTGRES_USER=apolonskyi
          POSTGRES_PASSWORD=Passw0rd!
          POSTGRES_DB=todo-list
      
    steps:
      - run: 'ls'
      - checkout
      - run: 'ls'
#       - run: './postgres-db.sh'
      - run: 'npm i'
      - run: 'npm start'
