version: 2.1
jobs:
  build:
    docker: 
      - image: postgres:11.1-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_HOST=localhost
          POSTGRES_USER=apolonskyi
          POSTGRES_PASSWORD=Passw0rd!
          POSTGRES_DB=todo-list
      - image: node:12.13.1
    steps:
      - run: 'exit'
      - checkout
      - run: 'ls'
      - run: 'env'
#       - run: './postgres-db.sh'
      - run: 'npm i'
      - run: 'npm start'
